 spring:
  application:
   name: JobSearch
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: Askar
    password: qwerty12345
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always


 server:
   port: 8080