 spring:
  application:
   name: JobSearch
  datasource:
    url: jdbc:h2:./db/job_search;AUTO_SERVER=TRUE
    username: Askar
    password: qwerty12345
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
    show-sql: false

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  mvc:
    static-path-pattern: /static/**
    log-request-details: false
  freemarker:
    expose-session-attributes: true


 server:
   port: 8081


 logging:
   level:
     root: info
     org:
       springframework:
         security: error
       hibernate:
         stat: error
         type: error
     sql: error
     web: error
   pattern:
     file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
   file:
     path: logs